In [69]:
import numpy as np

## DataTypes & Attributes

In [70]:
# Numpy's main dataype is "ndarray." (i.e 'n' dimensional Array).

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [71]:
type(a1)

numpy.ndarray

In [72]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## Attributes of a Numpy Array.

### Finding the Shape of the Array.

In [75]:
a1.shape

(3,)

In [76]:
a2.shape

(2, 3)

In [77]:
a3.shape

(3, 2, 3)

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### Knowing the Dimensions of the Array.

In [81]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### Knowing the Data Types of the Array.

In [82]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

### Knowing the Size of the Arrray.
It gives the number of elements in the array.

In [83]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Type of the Array.

In [84]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame from a NumPy Array.

In [85]:
import pandas as pd

df = pd.DataFrame(a2)

df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


# Creating NumPy Arrays.

In [86]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [87]:
sample_array.dtype

dtype('int64')

In [88]:
ones = np.ones([2, 3])


In [89]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
ones.dtype

dtype('float64')

In [91]:
type(ones)

numpy.ndarray

In [92]:
zeros = np.zeros((2, 3))

In [93]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [95]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[6, 5, 6, 3, 2],
       [6, 0, 8, 7, 2],
       [6, 5, 6, 9, 9]], dtype=int32)

In [96]:
random_array.size

15

In [97]:
random_array.shape

(3, 5)

In [98]:
random_array3 = np.random.random((5, 3))

random_array3

array([[0.89687705, 0.60875146, 0.34335932],
       [0.74405517, 0.37965191, 0.92500941],
       [0.59785221, 0.02765117, 0.68997563],
       [0.97332271, 0.29508526, 0.1896836 ],
       [0.99127407, 0.93617105, 0.32243042]])

In [99]:
random_array3.shape

(5, 3)

In [100]:
random_array3.size

15

In [101]:
random_array3 = np.random.rand(5, 3)

random_array3

array([[0.93185529, 0.00973002, 0.40263042],
       [0.52225094, 0.4826717 , 0.78975695],
       [0.69757156, 0.20617804, 0.72205299],
       [0.95677285, 0.15287567, 0.06754042],
       [0.44493919, 0.37852326, 0.68612555]])

In [102]:
# Pseudo random Numbers.

np.random.seed()