In [69]:
import numpy as np

## DataTypes & Attributes

In [70]:
# Numpy's main dataype is "ndarray." (i.e 'n' dimensional Array).

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [71]:
type(a1)

numpy.ndarray

In [72]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## Attributes of a Numpy Array.

### Finding the Shape of the Array.

In [75]:
a1.shape

(3,)

In [76]:
a2.shape

(2, 3)

In [77]:
a3.shape

(3, 2, 3)

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### Knowing the Dimensions of the Array.

In [81]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### Knowing the Data Types of the Array.

In [82]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

### Knowing the Size of the Arrray.
It gives the number of elements in the array.

In [83]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Type of the Array.

In [84]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame from a NumPy Array.

In [85]:
import pandas as pd

df = pd.DataFrame(a2)

df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


# Creating NumPy Arrays.

In [86]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [87]:
sample_array.dtype

dtype('int64')

In [88]:
ones = np.ones([2, 3])


In [89]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
ones.dtype

dtype('float64')

In [91]:
type(ones)

numpy.ndarray

In [92]:
zeros = np.zeros((2, 3))

In [93]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [95]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[6, 5, 6, 3, 2],
       [6, 0, 8, 7, 2],
       [6, 5, 6, 9, 9]], dtype=int32)

In [96]:
random_array.size

15

In [97]:
random_array.shape

(3, 5)

In [98]:
random_array3 = np.random.random((5, 3))

random_array3

array([[0.89687705, 0.60875146, 0.34335932],
       [0.74405517, 0.37965191, 0.92500941],
       [0.59785221, 0.02765117, 0.68997563],
       [0.97332271, 0.29508526, 0.1896836 ],
       [0.99127407, 0.93617105, 0.32243042]])

In [99]:
random_array3.shape

(5, 3)

In [100]:
random_array3.size

15

In [101]:
random_array3 = np.random.rand(5, 3)

random_array3

array([[0.93185529, 0.00973002, 0.40263042],
       [0.52225094, 0.4826717 , 0.78975695],
       [0.69757156, 0.20617804, 0.72205299],
       [0.95677285, 0.15287567, 0.06754042],
       [0.44493919, 0.37852326, 0.68612555]])

In [102]:
# Pseudo random Numbers.

np.random.seed()

# NumPy Random Seed

In [ ]:
# Pseudo random Numbers.

# np.random.seed()

In [ ]:
np.random.seed(seed=0)
# np.random.seed(seed=999)
# np.random.seed(seed=445)
# np.random.seed(seed=145)

random_array4 = np.random.randint(10, size=(5, 3))

random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [ ]:
random_array4.shape

(5, 3)

In [ ]:
np.random.seed(7)

random_array5 = np.random.random((5, 3))

random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [ ]:
random_array5 = np.random.random((5, 3))

random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

# Viewing Arrays and Matrices

In [ ]:
import numpy as np

In [ ]:
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[8, 9, 5],
       [6, 4, 1],
       [3, 2, 5],
       [8, 2, 3],
       [8, 6, 5]], dtype=int32)

In [ ]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 8, 9], dtype=int32)

In [ ]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [ ]:
a1 

array([1, 2, 3])

In [ ]:
a1[0]

np.int64(1)

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2[0]

array([1. , 2. , 3.3])

In [ ]:
a2[1]

array([4. , 5. , 6.5])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
a4 = np.random.randint(10, size=(2,3,4,5))

a4

array([[[[0, 9, 4, 5, 9],
         [3, 6, 4, 4, 6],
         [7, 2, 9, 9, 5],
         [7, 4, 3, 9, 5]],

        [[3, 3, 7, 4, 8],
         [3, 9, 1, 9, 1],
         [2, 8, 8, 6, 2],
         [7, 0, 7, 2, 2]],

        [[5, 0, 3, 5, 3],
         [8, 1, 4, 5, 3],
         [3, 2, 3, 4, 9],
         [5, 5, 6, 3, 6]]],


       [[[7, 8, 2, 5, 1],
         [2, 7, 0, 8, 0],
         [1, 4, 8, 3, 8],
         [8, 5, 4, 9, 1]],

        [[2, 5, 8, 3, 1],
         [4, 9, 5, 8, 6],
         [0, 0, 5, 5, 2],
         [6, 5, 1, 8, 0]],

        [[1, 9, 5, 9, 6],
         [9, 9, 8, 3, 0],
         [3, 4, 2, 3, 8],
         [9, 9, 4, 2, 3]]]], dtype=int32)

In [ ]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [ ]:
# Get the first 4 numbers of the inner most array.

a4[:, :, :, :4]



array([[[[0, 9, 4, 5],
         [3, 6, 4, 4],
         [7, 2, 9, 9],
         [7, 4, 3, 9]],

        [[3, 3, 7, 4],
         [3, 9, 1, 9],
         [2, 8, 8, 6],
         [7, 0, 7, 2]],

        [[5, 0, 3, 5],
         [8, 1, 4, 5],
         [3, 2, 3, 4],
         [5, 5, 6, 3]]],


       [[[7, 8, 2, 5],
         [2, 7, 0, 8],
         [1, 4, 8, 3],
         [8, 5, 4, 9]],

        [[2, 5, 8, 3],
         [4, 9, 5, 8],
         [0, 0, 5, 5],
         [6, 5, 1, 8]],

        [[1, 9, 5, 9],
         [9, 9, 8, 3],
         [3, 4, 2, 3],
         [9, 9, 4, 2]]]], dtype=int32)

In [ ]:
a4[:, :, :, 1]

array([[[9, 6, 2, 4],
        [3, 9, 8, 0],
        [0, 1, 2, 5]],

       [[8, 7, 4, 5],
        [5, 9, 0, 5],
        [9, 9, 4, 9]]], dtype=int32)

In [ ]:
a4[:2, :2, :1, :1]

array([[[[0]],

        [[3]]],


       [[[7]],

        [[2]]]], dtype=int32)

In [ ]:
a4[:, :, :, :1]

array([[[[0],
         [3],
         [7],
         [7]],

        [[3],
         [3],
         [2],
         [7]],

        [[5],
         [8],
         [3],
         [5]]],


       [[[7],
         [2],
         [1],
         [8]],

        [[2],
         [4],
         [0],
         [6]],

        [[1],
         [9],
         [3],
         [9]]]], dtype=int32)

# Manipulating & Comparing Arrays.

### Arithmetic 

In [ ]:
a1

array([1, 2, 3])

In [ ]:
ones = np.ones(3)

ones

array([1., 1., 1.])

In [ ]:
a1 + ones

array([2., 3., 4.])

In [ ]:
a1 - ones

array([0., 1., 2.])

In [ ]:
a1 * ones

array([1., 2., 3.])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# a2 * a3

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [ ]:
# np.reshape(a2, (1,3,3), copy=True)

# This Works, as it pads the remaning numbers with zero

a2_new = np.resize(a2, (1, 3, 3))

In [ ]:
a2_new * a3

array([[[ 1. ,  4. ,  9.9],
        [16. , 25. , 39. ],
        [ 7. , 16. , 29.7]],

       [[10. , 22. , 39.6],
        [52. , 70. , 97.5],
        [16. , 34. , 59.4]]])

In [ ]:
a1 / ones

array([1., 2., 3.])

In [ ]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [ ]:
# Floor Division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [ ]:
np.add(a1, ones)

array([2., 3., 4.])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a1 % 2

array([1, 0, 1])

In [ ]:
a1 / 2

array([0.5, 1. , 1.5])

In [ ]:
a2 % a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Manipulating Arrays 2

### Aggregation

Aggregation is the process of performing the same operations on a number of things.

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [ ]:
sum(listy_list)

6

In [ ]:
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
sum(a1)

np.int64(6)

In [ ]:
np.sum(a1)

np.int64(6)

Use Python's Methods (`sum()`) on Python datatypes and use NumPy's Methods on NumPy Arrays. (`np.sum()`).

In [ ]:
# Create a massive numpy array.

massive_array = np.random.random(100000)

massive_array.size


100000

In [ ]:
massive_array[:10]

array([0.85513203, 0.46883453, 0.23443602, 0.78912122, 0.47110382,
       0.77222324, 0.9278249 , 0.57804027, 0.69210356, 0.6119194 ])

In [ ]:
%timeit sum(massive_array) # Python's sum()

%timeit np.sum(massive_array) # NumPy's np.sum()


4.64 ms ± 451 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.7 μs ± 1.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
np.mean(a2)

np.float64(3.6333333333333333)

In [ ]:
np.max(a2)

np.float64(6.5)

In [ ]:
np.min(a2)

np.float64(1.0)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean.
np.std(a2)

np.float64(1.8226964152656422)

In [ ]:
# Variance = measure of the average degree to which each number is difference to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers.
np.var(a2)

np.float64(3.3222222222222224)

In [ ]:
# Standard deviatiion = Sq.root of var.
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)