In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main dataype is "ndarray." (i.e 'n' dimensional Array).

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## Attributes of a Numpy Array.

### Finding the Shape of the Array.

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1

array([1, 2, 3])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### Knowing the Dimensions of the Array.

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### Knowing the Data Types of the Array.

In [ ]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

### Knowing the Size of the Arrray.
It gives the number of elements in the array.

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Type of the Array.

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame from a NumPy Array.

In [ ]:
import pandas as pd

df = pd.DataFrame(a2)

df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


# Creating NumPy Arrays.

In [ ]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
ones = np.ones([2, 3])


In [ ]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
zeros = np.zeros((2, 3))

In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[0, 9, 7, 3, 5],
       [5, 3, 8, 3, 6],
       [1, 9, 5, 0, 3]], dtype=int32)

In [ ]:
random_array.size

15

In [ ]:
random_array.shape

(3, 5)

In [ ]:
random_array_2 = np.random.random((5, 3))

random_array_2

array([[0.02582458, 0.86329074, 0.84868342],
       [0.55826854, 0.63924488, 0.15820967],
       [0.74722608, 0.41942965, 0.62391077],
       [0.83709823, 0.74845773, 0.46334154],
       [0.27618364, 0.54542845, 0.04541248]])

In [ ]:
random_array_2.shape

(5, 3)

In [ ]:
random_array_2.size

15

In [ ]:
random_array_3 = np.random.rand(5, 3)

random_array_3

array([[0.12623493, 0.59144243, 0.76178752],
       [0.64097844, 0.89948207, 0.21949325],
       [0.87530338, 0.96964271, 0.95173117],
       [0.50145182, 0.63910297, 0.65063364],
       [0.66367236, 0.06582701, 0.06607316]])

In [ ]:
# Pseudo random Numbers.

np.random.seed()