# Comparison Operators.

In [18]:
import numpy as np

In [19]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [20]:
a1

array([1, 2, 3])

In [21]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [22]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [23]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [24]:
bool_array = a1 >= a2

bool_array

array([[ True,  True, False],
       [False, False, False]])

In [25]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [26]:
a1 > 5

array([False, False, False])

In [27]:
a1 < 5

array([ True,  True,  True])

In [28]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [30]:
a1 == a1

array([ True,  True,  True])

In [31]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])