# Creating NumPy Arrays.

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones([2, 3])


In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
ones.dtype

dtype('float64')

In [7]:
type(ones)

numpy.ndarray

In [ ]:
zeros = np.zeros((2, 3))

In [9]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[3, 9, 8, 7, 6],
       [5, 5, 9, 8, 3],
       [1, 6, 9, 6, 4]], dtype=int32)

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [ ]:
random_array2 = np.random.random((5, 3))

random_array2

array([[0.89998414, 0.02756046, 0.08110188],
       [0.58937699, 0.91209318, 0.27013579],
       [0.28111451, 0.51697873, 0.07738162],
       [0.97026037, 0.11589607, 0.43795425],
       [0.31303182, 0.62381116, 0.71375904]])

In [ ]:
random_array2.shape

(5, 3)

In [ ]:
random_array2.size

15

In [ ]:
random_array3 = np.random.rand(5, 3)

random_array3

array([[0.81355307, 0.96569806, 0.13820568],
       [0.32779252, 0.40932485, 0.7084375 ],
       [0.310824  , 0.41138564, 0.09450578],
       [0.47458712, 0.63165676, 0.85506506],
       [0.24382492, 0.32423252, 0.5209265 ]])

In [ ]:
# Pseudo random Numbers.

np.random.seed()