# Creating NumPy Arrays.

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones([2, 3])


In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
ones.dtype

dtype('float64')

In [7]:
type(ones)

numpy.ndarray

In [8]:
zeros = np.zeros((2, 3))

In [9]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[7, 4, 2, 5, 2],
       [0, 6, 2, 7, 6],
       [5, 7, 5, 0, 8]], dtype=int32)

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array_2 = np.random.random((5, 3))

random_array_2

array([[0.45706937, 0.86312504, 0.44664788],
       [0.73940546, 0.06898363, 0.13655291],
       [0.36467804, 0.18695927, 0.56547078],
       [0.63878154, 0.64127773, 0.74290444],
       [0.33559901, 0.80708695, 0.80656875]])

In [15]:
random_array_2.shape

(5, 3)

In [16]:
random_array_2.size

15

In [17]:
random_array_3 = np.random.rand(5, 3)

random_array_3

array([[0.31112181, 0.47366609, 0.19919764],
       [0.28655636, 0.59873904, 0.75363333],
       [0.53757717, 0.45554127, 0.48360345],
       [0.85228248, 0.53121597, 0.30907114],
       [0.11933411, 0.89114701, 0.71197371]])

In [18]:
# Pseudo random Numbers.

np.random.seed()

# NumPy Random Seed