# Creating NumPy Arrays.

In [1]:
import numpy as np

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones([2, 3])


In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
ones.dtype

dtype('float64')

In [7]:
type(ones)

numpy.ndarray

In [8]:
zeros = np.zeros((2, 3))

In [9]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)

range_array 

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0 ,10, size=(3,5))

random_array

array([[7, 6, 2, 5, 4],
       [1, 6, 6, 2, 6],
       [6, 1, 5, 3, 9]], dtype=int32)

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array2 = np.random.random((5, 3))

random_array2

array([[0.78535967, 0.35340661, 0.87271869],
       [0.55734708, 0.83810922, 0.49227479],
       [0.69739781, 0.37276596, 0.19838546],
       [0.96735911, 0.26812601, 0.74081361],
       [0.84017118, 0.16104442, 0.75123747]])

In [15]:
random_array2.shape

(5, 3)

In [16]:
random_array2.size

15

In [17]:
random_array3 = np.random.rand(5, 3)

random_array3

array([[0.50997086, 0.69319203, 0.4157162 ],
       [0.76283913, 0.70322984, 0.65758259],
       [0.27733408, 0.27489301, 0.73793852],
       [0.28049701, 0.1195384 , 0.14243473],
       [0.05289979, 0.8401956 , 0.46391228]])

In [18]:
# Pseudo random Numbers.

#np.random.seed()

# NumPy Random Seed

In [ ]:
# Pseudo random Numbers.

# np.random.seed()

In [42]:
np.random.seed(seed=0)
# np.random.seed(seed=999)
# np.random.seed(seed=445)
# np.random.seed(seed=145)

random_array4 = np.random.randint(10, size=(5, 3))

random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [21]:
random_array4.shape

(5, 3)

In [45]:
np.random.seed(7)

random_array5 = np.random.random((5, 3))

random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [46]:
random_array5 = np.random.random((5, 3))

random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])