# Reshaping and Transposing

In [28]:
import numpy as np

In [29]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a2.shape

(2, 3)

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a3.shape

(2, 3, 3)

In [34]:
# a2 * a3

# Error: ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [35]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a2_reshape = a2.reshape(2, 3, 1)

a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [38]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [39]:
# Transponse = switches the axis. (Reverse the axis)
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a2.shape

(2, 3)

In [41]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [42]:
a2.T.shape

(3, 2)

In [43]:
a3.shape

(2, 3, 3)

In [44]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [45]:
a3.T.shape

(3, 3, 2)

# Dot Product vs Element Wise

In [46]:
np.random.seed(0)

In [47]:
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [48]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [49]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [50]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [ ]:
# Element-wise multiplication (Hadamard product)

mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [64]:
# Dot product 'np.dot' or '@'

# np.dot(mat1, mat2)
# Error: ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

# mat1 @ mat2
# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [56]:
# Transpose mat 1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [58]:
mat1.T.shape, mat2.shape

((3, 5), (5, 3))

In [60]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [59]:
mat3 = np.dot(mat1, mat2.T)

mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)