# Viewing Arrays and Matrices

In [33]:
import numpy as np

In [34]:
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[6, 3, 5],
       [7, 0, 1],
       [7, 8, 2],
       [1, 7, 8],
       [8, 4, 3]], dtype=int32)

In [35]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [36]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [37]:
a1 

array([1, 2, 3])

In [38]:
a1[0]

np.int64(1)

In [39]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a2.shape

(2, 3)

In [41]:
a2[0]

array([1. , 2. , 3.3])

In [42]:
a2[1]

array([4. , 5. , 6.5])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3.shape

(2, 3, 3)

In [45]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10, size=(2,3,4,5))

a4

array([[[[1, 4, 3, 5, 8],
         [8, 1, 4, 9, 5],
         [6, 1, 7, 1, 0],
         [5, 3, 5, 4, 9]],

        [[2, 6, 8, 4, 0],
         [9, 4, 0, 9, 9],
         [4, 0, 7, 7, 4],
         [8, 1, 8, 3, 6]],

        [[0, 2, 8, 6, 7],
         [4, 4, 7, 4, 0],
         [8, 1, 5, 3, 3],
         [1, 2, 5, 6, 5]]],


       [[[2, 6, 0, 6, 3],
         [8, 1, 7, 3, 0],
         [0, 4, 1, 8, 7],
         [2, 3, 2, 1, 2]],

        [[9, 2, 4, 0, 3],
         [6, 8, 7, 1, 3],
         [9, 3, 3, 3, 1],
         [9, 5, 5, 6, 9]],

        [[9, 4, 2, 3, 2],
         [9, 8, 9, 3, 6],
         [7, 7, 4, 4, 6],
         [5, 0, 9, 4, 1]]]], dtype=int32)

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get the first 4 numbers of the inner most array.

a4[:, :, :, :4]



array([[[[1, 4, 3, 5],
         [8, 1, 4, 9],
         [6, 1, 7, 1],
         [5, 3, 5, 4]],

        [[2, 6, 8, 4],
         [9, 4, 0, 9],
         [4, 0, 7, 7],
         [8, 1, 8, 3]],

        [[0, 2, 8, 6],
         [4, 4, 7, 4],
         [8, 1, 5, 3],
         [1, 2, 5, 6]]],


       [[[2, 6, 0, 6],
         [8, 1, 7, 3],
         [0, 4, 1, 8],
         [2, 3, 2, 1]],

        [[9, 2, 4, 0],
         [6, 8, 7, 1],
         [9, 3, 3, 3],
         [9, 5, 5, 6]],

        [[9, 4, 2, 3],
         [9, 8, 9, 3],
         [7, 7, 4, 4],
         [5, 0, 9, 4]]]], dtype=int32)

In [50]:
a4[:, :, :, 1]

array([[[4, 1, 1, 3],
        [6, 4, 0, 1],
        [2, 4, 1, 2]],

       [[6, 1, 4, 3],
        [2, 8, 3, 5],
        [4, 8, 7, 0]]], dtype=int32)

In [51]:
a4[:2, :2, :1, :1]

array([[[[1]],

        [[2]]],


       [[[2]],

        [[9]]]], dtype=int32)

In [52]:
a4[:, :, :, :1]

array([[[[1],
         [8],
         [6],
         [5]],

        [[2],
         [9],
         [4],
         [8]],

        [[0],
         [4],
         [8],
         [1]]],


       [[[2],
         [8],
         [0],
         [2]],

        [[9],
         [6],
         [9],
         [9]],

        [[9],
         [9],
         [7],
         [5]]]], dtype=int32)

# Manipulating & Comparing Arrays.

### Arithmetic 

In [53]:
a1

array([1, 2, 3])

In [54]:
ones = np.ones(3)

ones

array([1., 1., 1.])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
a1 - ones

array([0., 1., 2.])

In [57]:
a1 * ones

array([1., 2., 3.])

In [58]:
a1

array([1, 2, 3])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [61]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [62]:
# a2 * a3

# Error: ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [63]:
# np.reshape(a2, (1,3,3), copy=True)

# This Works, as it pads the remaning numbers with zero

a2_new = np.resize(a2, (1, 3, 3))

In [64]:
a2_new * a3

array([[[ 1. ,  4. ,  9.9],
        [16. , 25. , 39. ],
        [ 7. , 16. , 29.7]],

       [[10. , 22. , 39.6],
        [52. , 70. , 97.5],
        [16. , 34. , 59.4]]])

In [65]:
a1 / ones

array([1., 2., 3.])

In [66]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [67]:
# Floor Division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [68]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [69]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [70]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [71]:
np.add(a1, ones)

array([2., 3., 4.])

In [72]:
a1

array([1, 2, 3])

In [73]:
a1 % 2

array([1, 0, 1])

In [74]:
a1 / 2

array([0.5, 1. , 1.5])

In [75]:
a2 % a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [77]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Manipulating Arrays 2

### Aggregation

Aggregation is the process of performing the same operations on a number of things.

In [78]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [79]:
sum(listy_list)

6

In [80]:
a1

array([1, 2, 3])

In [81]:
type(a1)

numpy.ndarray

In [82]:
sum(a1)

np.int64(6)

In [83]:
np.sum(a1)

np.int64(6)

Use Python's Methods (`sum()`) on Python datatypes and use NumPy's Methods on NumPy Arrays. (`np.sum()`).

In [84]:
# Create a massive numpy array.

massive_array = np.random.random(100000)

massive_array.size


100000

In [85]:
massive_array[:10]

array([0.46986851, 0.52441147, 0.83232667, 0.19287935, 0.30083259,
       0.58754646, 0.29903405, 0.18656218, 0.09376591, 0.14916179])

In [86]:
%timeit sum(massive_array) # Python's sum()

%timeit np.sum(massive_array) # NumPy's np.sum()


4.56 ms ± 130 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.6 μs ± 1.54 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [87]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
np.mean(a2)

np.float64(3.6333333333333333)

In [89]:
np.max(a2)

np.float64(6.5)

In [90]:
np.min(a2)

np.float64(1.0)

In [91]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean.
np.std(a2)

np.float64(1.8226964152656422)

In [92]:
# Variance = measure of the average degree to which each number is difference to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers.
np.var(a2)

np.float64(3.3222222222222224)

In [93]:
# Standard deviatiion = Sq.root of var.
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)