# Viewing Arrays and Matrices

In [54]:
import numpy as np

In [55]:
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[8, 2, 2],
       [9, 7, 3],
       [5, 1, 9],
       [9, 8, 5],
       [5, 6, 9]], dtype=int32)

In [56]:
np.unique(random_array)

array([1, 2, 3, 5, 6, 7, 8, 9], dtype=int32)

In [57]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [58]:
a1 

array([1, 2, 3])

In [59]:
a1[0]

np.int64(1)

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [61]:
a2.shape

(2, 3)

In [62]:
a2[0]

array([1. , 2. , 3.3])

In [63]:
a2[1]

array([4. , 5. , 6.5])

In [64]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [65]:
a3.shape

(2, 3, 3)

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [68]:
a4 = np.random.randint(10, size=(2,3,4,5))

a4

array([[[[8, 5, 3, 2, 9],
         [3, 7, 0, 7, 5],
         [7, 7, 9, 5, 7],
         [7, 5, 8, 5, 5]],

        [[2, 6, 1, 9, 7],
         [9, 1, 7, 4, 0],
         [8, 6, 4, 0, 0],
         [0, 7, 2, 2, 4]],

        [[1, 2, 8, 5, 2],
         [1, 7, 3, 0, 0],
         [0, 6, 9, 4, 2],
         [9, 6, 2, 9, 7]]],


       [[[8, 6, 8, 5, 1],
         [5, 6, 1, 0, 6],
         [3, 4, 0, 9, 1],
         [9, 3, 2, 1, 3]],

        [[9, 6, 4, 6, 6],
         [0, 2, 6, 6, 2],
         [1, 7, 4, 9, 3],
         [7, 9, 2, 8, 9]],

        [[5, 9, 9, 6, 8],
         [5, 0, 0, 3, 3],
         [2, 5, 6, 7, 2],
         [4, 5, 8, 3, 6]]]], dtype=int32)

In [69]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [70]:
# Get the first 4 numbers of the inner most array.

a4[:, :, :, :4]



array([[[[8, 5, 3, 2],
         [3, 7, 0, 7],
         [7, 7, 9, 5],
         [7, 5, 8, 5]],

        [[2, 6, 1, 9],
         [9, 1, 7, 4],
         [8, 6, 4, 0],
         [0, 7, 2, 2]],

        [[1, 2, 8, 5],
         [1, 7, 3, 0],
         [0, 6, 9, 4],
         [9, 6, 2, 9]]],


       [[[8, 6, 8, 5],
         [5, 6, 1, 0],
         [3, 4, 0, 9],
         [9, 3, 2, 1]],

        [[9, 6, 4, 6],
         [0, 2, 6, 6],
         [1, 7, 4, 9],
         [7, 9, 2, 8]],

        [[5, 9, 9, 6],
         [5, 0, 0, 3],
         [2, 5, 6, 7],
         [4, 5, 8, 3]]]], dtype=int32)

In [71]:
a4[:, :, :, 1]

array([[[5, 7, 7, 5],
        [6, 1, 6, 7],
        [2, 7, 6, 6]],

       [[6, 6, 4, 3],
        [6, 2, 7, 9],
        [9, 0, 5, 5]]], dtype=int32)

In [72]:
a4[:2, :2, :1, :1]

array([[[[8]],

        [[2]]],


       [[[8]],

        [[9]]]], dtype=int32)

In [73]:
a4[:, :, :, :1]

array([[[[8],
         [3],
         [7],
         [7]],

        [[2],
         [9],
         [8],
         [0]],

        [[1],
         [1],
         [0],
         [9]]],


       [[[8],
         [5],
         [3],
         [9]],

        [[9],
         [0],
         [1],
         [7]],

        [[5],
         [5],
         [2],
         [4]]]], dtype=int32)

# Manipulating & Comparing Arrays.

### Arithmetic 

In [74]:
a1

array([1, 2, 3])

In [75]:
ones = np.ones(3)

ones

array([1., 1., 1.])

In [76]:
a1 + ones

array([2., 3., 4.])

In [77]:
a1 - ones

array([0., 1., 2.])

In [78]:
a1 * ones

array([1., 2., 3.])

In [79]:
a1

array([1, 2, 3])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
# a2 * a3

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [84]:
# np.reshape(a2, (1,3,3), copy=True)

# This Works, as it pads the remaning numbers with zero

a2_new = np.resize(a2, (1, 3, 3))

In [85]:
a2_new * a3

array([[[ 1. ,  4. ,  9.9],
        [16. , 25. , 39. ],
        [ 7. , 16. , 29.7]],

       [[10. , 22. , 39.6],
        [52. , 70. , 97.5],
        [16. , 34. , 59.4]]])

In [86]:
a1 / ones

array([1., 2., 3.])

In [87]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [88]:
# Floor Division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [89]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [90]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [91]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [92]:
np.add(a1, ones)

array([2., 3., 4.])

In [93]:
a1

array([1, 2, 3])

In [94]:
a1 % 2

array([1, 0, 1])

In [95]:
a1 / 2

array([0.5, 1. , 1.5])

In [96]:
a2 % a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [98]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Manipulating Arrays 2

### Aggregation

Aggregation is the process of performing the same operations on a number of things.

In [99]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [100]:
sum(listy_list)

6

In [101]:
a1

array([1, 2, 3])

In [102]:
type(a1)

numpy.ndarray

In [103]:
sum(a1)

np.int64(6)

In [104]:
np.sum(a1)

np.int64(6)

Use Python's Methods (`sum()`) on Python datatypes and use NumPy's Methods on NumPy Arrays. (`np.sum()`).

In [111]:
# Create a massive numpy array.

massive_array = np.random.random(100000)

massive_array.size


100000

In [113]:
massive_array[:10]

array([0.85513203, 0.46883453, 0.23443602, 0.78912122, 0.47110382,
       0.77222324, 0.9278249 , 0.57804027, 0.69210356, 0.6119194 ])

In [116]:
%timeit sum(massive_array) # Python's sum()

%timeit np.sum(massive_array) # NumPy's np.sum()


4.64 ms ± 451 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.7 μs ± 1.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [117]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [118]:
np.mean(a2)

np.float64(3.6333333333333333)

In [119]:
np.max(a2)

np.float64(6.5)

In [120]:
np.min(a2)

np.float64(1.0)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean.
np.std(a2)

np.float64(1.8226964152656422)

In [ ]:
# Variance = measure of the average degree to which each number is difference to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers.
np.var(a2)

np.float64(3.3222222222222224)

In [ ]:
# Standard deviatiion = Sq.root of var.
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)