# Viewing Arrays and Matrices

In [3]:
import numpy as np

In [4]:
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[3, 6, 6],
       [0, 4, 1],
       [1, 3, 4],
       [7, 6, 3],
       [3, 3, 7]], dtype=int32)

In [5]:
np.unique(random_array)

array([0, 1, 3, 4, 6, 7], dtype=int32)

In [6]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a1 

array([1, 2, 3])

In [8]:
a1[0]

np.int64(1)

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a2.shape

(2, 3)

In [11]:
a2[0]

array([1. , 2. , 3.3])

In [12]:
a2[1]

array([4. , 5. , 6.5])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [17]:
a4 = np.random.randint(10, size=(2,3,4,5))

a4

array([[[[4, 7, 1, 2, 9],
         [7, 3, 6, 2, 6],
         [4, 0, 4, 7, 1],
         [6, 0, 0, 0, 8]],

        [[5, 1, 8, 7, 6],
         [7, 0, 1, 7, 9],
         [2, 6, 1, 8, 3],
         [2, 9, 6, 1, 6]],

        [[4, 5, 5, 0, 9],
         [7, 6, 8, 9, 9],
         [2, 2, 1, 8, 5],
         [6, 2, 7, 1, 3]]],


       [[[0, 8, 0, 4, 1],
         [8, 9, 8, 5, 5],
         [3, 9, 1, 8, 8],
         [4, 9, 2, 5, 2]],

        [[7, 9, 6, 9, 1],
         [5, 3, 6, 7, 1],
         [0, 4, 8, 2, 0],
         [2, 6, 9, 9, 0]],

        [[1, 6, 1, 7, 8],
         [1, 3, 5, 9, 0],
         [3, 8, 6, 3, 4],
         [2, 0, 5, 3, 3]]]], dtype=int32)

In [18]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [19]:
# Get the first 4 numbers of the inner most array.

a4[:, :, :, :4]



array([[[[4, 7, 1, 2],
         [7, 3, 6, 2],
         [4, 0, 4, 7],
         [6, 0, 0, 0]],

        [[5, 1, 8, 7],
         [7, 0, 1, 7],
         [2, 6, 1, 8],
         [2, 9, 6, 1]],

        [[4, 5, 5, 0],
         [7, 6, 8, 9],
         [2, 2, 1, 8],
         [6, 2, 7, 1]]],


       [[[0, 8, 0, 4],
         [8, 9, 8, 5],
         [3, 9, 1, 8],
         [4, 9, 2, 5]],

        [[7, 9, 6, 9],
         [5, 3, 6, 7],
         [0, 4, 8, 2],
         [2, 6, 9, 9]],

        [[1, 6, 1, 7],
         [1, 3, 5, 9],
         [3, 8, 6, 3],
         [2, 0, 5, 3]]]], dtype=int32)

In [20]:
a4[:, :, :, 1]

array([[[7, 3, 0, 0],
        [1, 0, 6, 9],
        [5, 6, 2, 2]],

       [[8, 9, 9, 9],
        [9, 3, 4, 6],
        [6, 3, 8, 0]]], dtype=int32)

In [21]:
a4[:2, :2, :1, :1]

array([[[[4]],

        [[5]]],


       [[[0]],

        [[7]]]], dtype=int32)

In [22]:
a4[:, :, :, :1]

array([[[[4],
         [7],
         [4],
         [6]],

        [[5],
         [7],
         [2],
         [2]],

        [[4],
         [7],
         [2],
         [6]]],


       [[[0],
         [8],
         [3],
         [4]],

        [[7],
         [5],
         [0],
         [2]],

        [[1],
         [1],
         [3],
         [2]]]], dtype=int32)

# Manipulating & Comparing Arrays.

### Arithmetic 

In [23]:
a1

array([1, 2, 3])

In [24]:
ones = np.ones(3)

ones

array([1., 1., 1.])

In [25]:
a1 + ones

array([2., 3., 4.])

In [26]:
a1 - ones

array([0., 1., 2.])

In [27]:
a1 * ones

array([1., 2., 3.])

In [28]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [30]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
# a2 * a3

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [33]:
# np.reshape(a2, (1,3,3), copy=True)

# This Works, as it pads the remaning numbers with zero

a2_new = np.resize(a2, (1, 3, 3))

In [34]:
a2_new * a3

array([[[ 1. ,  4. ,  9.9],
        [16. , 25. , 39. ],
        [ 7. , 16. , 29.7]],

       [[10. , 22. , 39.6],
        [52. , 70. , 97.5],
        [16. , 34. , 59.4]]])

In [35]:
a1 / ones

array([1., 2., 3.])

In [36]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [37]:
# Floor Division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [40]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [41]:
np.add(a1, ones)

array([2., 3., 4.])

In [42]:
a1

array([1, 2, 3])

In [43]:
a1 % 2

array([1, 0, 1])

In [44]:
a1 / 2

array([0.5, 1. , 1.5])

In [45]:
a2 % a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [47]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])