# Reshaping and Transposing

In [1]:
import numpy as np

In [2]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [3]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a2.shape

(2, 3)

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [ ]:
# a2 * a3

# Error: ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [8]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a2_reshape = a2.reshape(2, 3, 1)

a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [13]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
# Transponse = switches the axis. (Reverse the axis)
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a2.shape

(2, 3)

In [17]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [19]:
a2.T.shape

(3, 2)

In [21]:
a3.shape

(2, 3, 3)

In [22]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [23]:
a3.T.shape

(3, 3, 2)