# Sorting Arrays.

In [26]:
import numpy as np

In [27]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [28]:
random_array = np.random.randint(10, size =(3, 5))

random_array

array([[5, 8, 2, 0, 5],
       [9, 4, 8, 5, 5],
       [4, 5, 1, 6, 6]], dtype=int32)

In [29]:
np.sort(random_array)

array([[0, 2, 5, 5, 8],
       [4, 5, 5, 8, 9],
       [1, 4, 5, 6, 6]], dtype=int32)

In [30]:
random_array

array([[5, 8, 2, 0, 5],
       [9, 4, 8, 5, 5],
       [4, 5, 1, 6, 6]], dtype=int32)

In [31]:
np.argsort(random_array)

array([[3, 2, 0, 4, 1],
       [1, 3, 4, 2, 0],
       [2, 0, 1, 3, 4]])

In [32]:
a1

array([1, 2, 3])

In [33]:
np.argsort(a1)

array([0, 1, 2])

In [34]:
np.argmin(a1)

np.int64(0)

In [35]:
np.argmax(a1)

np.int64(2)

In [36]:
random_array

array([[5, 8, 2, 0, 5],
       [9, 4, 8, 5, 5],
       [4, 5, 1, 6, 6]], dtype=int32)

In [37]:
# It is giving the max value for each "Rows". {i.e axis 0 is 'row'}
np.argmax(random_array, axis=0)     # {Rows}

array([1, 0, 1, 2, 2])

In [38]:
# It is giving the max value for each "Column". {i.e axis 1 is 'column'}
np.argmax(random_array, axis=1)     # {Columns}

array([1, 0, 3])

In [41]:
random_array

array([[5, 8, 2, 0, 5],
       [9, 4, 8, 5, 5],
       [4, 5, 1, 6, 6]], dtype=int32)

In [39]:
# It is giving the max value for each "Rows". {i.e axis 0 is 'row'}
np.argmin(random_array, axis=0)     # {Rows}

array([2, 1, 2, 0, 0])

In [40]:
# It is giving the max value for each "Column". {i.e axis 1 is 'column'}
np.argmin(random_array, axis=1)     # {Columns}

array([3, 1, 2])