# Viewing Arrays and Matrices

In [81]:
import numpy as np

In [82]:
random_array = np.random.randint(10, size=(5, 3))

random_array

array([[8, 9, 5],
       [6, 4, 1],
       [3, 2, 5],
       [8, 2, 3],
       [8, 6, 5]], dtype=int32)

In [83]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 8, 9], dtype=int32)

In [84]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [85]:
a1 

array([1, 2, 3])

In [86]:
a1[0]

np.int64(1)

In [87]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
a2.shape

(2, 3)

In [89]:
a2[0]

array([1. , 2. , 3.3])

In [90]:
a2[1]

array([4. , 5. , 6.5])

In [91]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [92]:
a3.shape

(2, 3, 3)

In [93]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [95]:
a4 = np.random.randint(10, size=(2,3,4,5))

a4

array([[[[0, 9, 4, 5, 9],
         [3, 6, 4, 4, 6],
         [7, 2, 9, 9, 5],
         [7, 4, 3, 9, 5]],

        [[3, 3, 7, 4, 8],
         [3, 9, 1, 9, 1],
         [2, 8, 8, 6, 2],
         [7, 0, 7, 2, 2]],

        [[5, 0, 3, 5, 3],
         [8, 1, 4, 5, 3],
         [3, 2, 3, 4, 9],
         [5, 5, 6, 3, 6]]],


       [[[7, 8, 2, 5, 1],
         [2, 7, 0, 8, 0],
         [1, 4, 8, 3, 8],
         [8, 5, 4, 9, 1]],

        [[2, 5, 8, 3, 1],
         [4, 9, 5, 8, 6],
         [0, 0, 5, 5, 2],
         [6, 5, 1, 8, 0]],

        [[1, 9, 5, 9, 6],
         [9, 9, 8, 3, 0],
         [3, 4, 2, 3, 8],
         [9, 9, 4, 2, 3]]]], dtype=int32)

In [96]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [97]:
# Get the first 4 numbers of the inner most array.

a4[:, :, :, :4]



array([[[[0, 9, 4, 5],
         [3, 6, 4, 4],
         [7, 2, 9, 9],
         [7, 4, 3, 9]],

        [[3, 3, 7, 4],
         [3, 9, 1, 9],
         [2, 8, 8, 6],
         [7, 0, 7, 2]],

        [[5, 0, 3, 5],
         [8, 1, 4, 5],
         [3, 2, 3, 4],
         [5, 5, 6, 3]]],


       [[[7, 8, 2, 5],
         [2, 7, 0, 8],
         [1, 4, 8, 3],
         [8, 5, 4, 9]],

        [[2, 5, 8, 3],
         [4, 9, 5, 8],
         [0, 0, 5, 5],
         [6, 5, 1, 8]],

        [[1, 9, 5, 9],
         [9, 9, 8, 3],
         [3, 4, 2, 3],
         [9, 9, 4, 2]]]], dtype=int32)

In [98]:
a4[:, :, :, 1]

array([[[9, 6, 2, 4],
        [3, 9, 8, 0],
        [0, 1, 2, 5]],

       [[8, 7, 4, 5],
        [5, 9, 0, 5],
        [9, 9, 4, 9]]], dtype=int32)

In [99]:
a4[:2, :2, :1, :1]

array([[[[0]],

        [[3]]],


       [[[7]],

        [[2]]]], dtype=int32)

In [100]:
a4[:, :, :, :1]

array([[[[0],
         [3],
         [7],
         [7]],

        [[3],
         [3],
         [2],
         [7]],

        [[5],
         [8],
         [3],
         [5]]],


       [[[7],
         [2],
         [1],
         [8]],

        [[2],
         [4],
         [0],
         [6]],

        [[1],
         [9],
         [3],
         [9]]]], dtype=int32)